/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.kyunggi.medinology;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int diseaseoneTextView=0x7f050001;
        public static final int diseasetwoTextView=0x7f050002;
        public static final int showresultTextView1=0x7f050000;
    }
    public static final class layout {
        public static final int showresult=0x7f020000;
    }
    public static final class raw {
        public static final int diseases=0x7f030000;
        public static final int drugs=0x7f030001;
        public static final int symptoms=0x7f030002;
        public static final int weights=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
